main:
	g++ exercicio5.cpp glad.c -lglfw -ldl -o exercicio5.out
	g++ exercicio7.cpp glad.c -lglfw -ldl -o exercicio7.out
	g++ exercicio8.cpp glad.c -lglfw -ldl -o exercicio8.out
	g++ exercicio9.cpp glad.c -lglfw -ldl -o exercicio9.out
