
main:
	g++ circulo.cpp ../glad.c -lglfw -ldl -o circulo.out
	g++ octagono.cpp ../glad.c -lglfw -ldl -o octagono.out
	g++ pentagono.cpp ../glad.c -lglfw -ldl -o pentagono.out
	g++ estrela.cpp ../glad.c -lglfw -ldl -o estrela.out
	g++ pizza.cpp ../glad.c -lglfw -ldl -o pizza.out
	g++ pacman.cpp ../glad.c -lglfw -ldl -o pacman.out
